version: "2"
services:
  web_app:
    hostname: doghouse
    container_name: app
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} #Env Variable - Set Manually at runtime